---
title: "<NuxtErrorBoundary>"
description: "Компонент <NuxtErrorBoundary> обрабатывает клиентские ошибки, происходящие в его слоте по умолчанию."
links:
  - label: Source
    icon: i-simple-icons-github
    to: https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/nuxt-error-boundary.vue
    size: xs
---

::tip
`<NuxtErrorBoundary>` использует хук [`onErrorCaptured`](https://vuejs.org/api/composition-api-lifecycle.html#onerrorcaptured) из Vue под капотом.
::

## События

- `@error`: Событие, которое генерируется, когда слот по умолчанию компонента выбрасывает ошибку.

  ```vue
  <template>
    <NuxtErrorBoundary @error="logSomeError">
      <!-- ... -->
    </NuxtErrorBoundary>
  </template>
  ```

## Слоты

- `#error`: Укажите резервный контент для отображения в случае ошибки.

  ```vue
    <template>
      <NuxtErrorBoundary>
        <!-- ... -->
        <template #error="{ error, clearError }">
          <p>Произошла ошибка: {{ error }}</p>

          <button @click="clearError">Очистить ошибку</button>
        </template>
      </NuxtErrorBoundary>
    </template>
  ```

:read-more{to="/docs/getting-started/error-handling"}

## Примеры

### Доступ к `error` и `clearError` в скрипте

Вы можете получить доступ к свойствам `error` и `clearError` внутри скрипта компонента следующим образом:

```vue
<template>
  <NuxtErrorBoundary ref="errorBoundary">
    <!-- ... -->
  </NuxtErrorBoundary>
</template>

<script setup lang="ts">
const errorBoundary = useTemplateRef('errorBoundary')

// errorBoundary.value?.error
// errorBoundary.value?.clearError()
</script>
```